### ISSUE TITLE
Remember port number and potentially host password

### ISSUE THREAD

**Issue by errietta** [nickdesaulniers/fxos-irc#85]
The port number for the server settings should be remembered, and perhaps we can have a checkbox to remember the host password. @nickdesaulniers any way to do that securely?

**Comment by nickdesaulniers** [comment]
As long as we guard against XSS attacks, I'm not sure storing it in plaintext matters.  You could store the password encrypted, and decrypt it, but if the app is vulnerable to XSS, then an attacker could just call the decrypt function.  That makes me think about our current support for links.  I should triple check one can't abuse that for XSS.

**Comment by errietta** [comment]
R? @nickdesaulniers
